---
- name: Gather facts about VPC 
  ec2_vpc_net_facts:
    region: "{{ region }}"
    filters:
      "tag:Name": "{{ vpc_name }}"
  register: vpc_facts

- name: Set VPC ID fact
  set_fact:
    vpc_id: "{{ vpc_facts.vpcs[0].id }}"

- name: Create Subnets
  ec2_vpc_subnet:
    state: present
    vpc_id: "{{ vpc_id }}"
    cidr: "{{ item.subnet_cidr }}"
    az: "{{ item.subnet_az }}"
    map_public: "{{ item.subnet_map_public | default ('no') }}"
    resource_tags:
      Name: "{{ item.subnet_name }}"
      VPCname: "{{ vpc_name }}"
  with_items: "{{ subnets }}"
  register: subnets_output