---
- name: Gather facts about VPC 
  ec2_vpc_net_facts:
    region: "{{ region }}"
    filters:
      "tag:Name": "{{ vpc_name }}"
  register: vpc_facts

- name: Set VPC ID fact
  set_fact:
    vpc_id: "{{ vpc_facts.vpcs[0].id }}"

- name: Create Subnets
  ec2_vpc_subnet:
    state: present
    vpc_id: "{{ vpc_id }}"
    cidr: "{{ item.subnet_cidr }}"
    az: "{{ item.subnet_az }}"
    map_public: "{{ item.subnet_map_public | default ('no') }}"
    resource_tags:
      Name: "{{ item.subnet_name }}"
      VPCname: "{{ vpc_name }}"
  with_items: "{{ subnets }}"
  register: subnets_output

# - name: Store subnet fact for further use
#   set_fact:
#     subnets_output: "{{ subnets_output }}"

# - name: Gather info about public Subnets for further use (NATGW creation)
#   ec2_vpc_subnet_facts:
#     filters:
#       vpc-id: "{{ vpc_id }}"
#       "tag:Name": "*Public*"
#   register: public_subnets

# - name: Store subnet facts for further use (NATGW creation)
#   set_fact:
#     public_subnet_ids: "{{ public_subnets | json_query ('subnets[*].subnet_id') }}"